package org.grails.demo.soap.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2015-07-14T10:13:17.490-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://demo.grails.org/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebResult(name = "Customer", targetNamespace = "")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "http://demo.grails.org/", className = "org.grails.demo.soap.customer.GetCustomer")
    @WebMethod(operationName = "GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "http://demo.grails.org", className = "org.grails.demo.soap.customer.GetCustomerResponse")
    public org.grails.demo.soap.customer.Customer getCustomer(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId
    );

    @WebResult(name = "Customers", targetNamespace = "")
    @RequestWrapper(localName = "GetCustomers", targetNamespace = "http://demo.grails.org/", className = "org.grails.demo.soap.customer.GetCustomers")
    @WebMethod(operationName = "GetCustomers")
    @ResponseWrapper(localName = "GetCustomersResponse", targetNamespace = "http://demo.grails.org", className = "org.grails.demo.soap.customer.GetCustomersResponse")
    public java.util.List<org.grails.demo.soap.customer.Customer> getCustomers();

    @WebResult(name = "Customer", targetNamespace = "")
    @RequestWrapper(localName = "MakePayment", targetNamespace = "http://demo.grails.org/", className = "org.grails.demo.soap.customer.MakePayment")
    @WebMethod(operationName = "MakePayment")
    @ResponseWrapper(localName = "MakePaymentResponse", targetNamespace = "http://demo.grails.org", className = "org.grails.demo.soap.customer.MakePaymentResponse")
    public org.grails.demo.soap.customer.Customer makePayment(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId,
        @WebParam(name = "paymentDate", targetNamespace = "")
        java.util.Date paymentDate,
        @WebParam(name = "paymentAmount", targetNamespace = "")
        java.lang.Double paymentAmount
    );
}
